extends Area2D


@onready var kitty_boo = get_node("../kitty_boo")


func _on_body_entered(body):
	if (body.name == "kitty_boo"):
		#game_manager.confirm_box()
		kitty_boo.call_deferred("free")
		$AnimatedSprite2D.play("default")
		$"../level_5_theme".stop()
		$"../box_player_end".play()
		$"/root/Global".StarTotal += $"../GameMgr".points
		print(str("Total Points: ",$"/root/Global".StarTotal))
		await get_tree().create_timer(11.0).timeout
		get_tree().change_scene_to_file("res://scenes/5-e.tscn")
